name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi
      - name: Install dev tools (pytest, pre-commit)
        run: |
          pip install pytest pre-commit
      - name: Run pre-commit (lint/format)
        run: pre-commit run --all-files
      - name: Sanity check – import app
        run: |
          python - << 'PY'
          import importlib
          m = importlib.import_module('wsgi')
          assert hasattr(m, 'app'), 'wsgi.app is missing'
          print('WSGI app import OK')
          PY
      - name: Flask CLI check
        env:
          FLASK_APP: wsgi:app
        run: |
          python -m flask routes | head -n 10
      - name: Run tests
        run: |
          pytest -q
